GoodNewsAggregator/GoodNewsAggregator/Controllers/NavigationController.cs
using GoodNewsAggregator.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using GoodNewsAggregator.Core.Services.Interfaces.Enums;
using GoodNewsAggregator.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using Serilog;

namespace GoodNewsAggregator.Controllers
{
    [Authorize]
    public class NavigationController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IRssService _rssService;
        private readonly IMapper _mapper;
        private readonly IConfiguration _configuration;

        public NavigationController(IArticleService articleService, IRssService rssService, IMapper mapper, IConfiguration configuration)
        {
            _articleService = articleService;
            _rssService = rssService;
            _mapper = mapper;
            _configuration = configuration;
        }

        public async Task<IActionResult> Main(int page = 1, SortByOption sortBy = SortByOption.DateTime)
        {
            var hasNulls = false;

            var pageSize = 0;
            if (!Int32.TryParse(_configuration["Constants:PageSize"], out pageSize))
            {
                Log.Error("Constants:PageSize field is not valid");
                pageSize = 20;
            }

            var news = (await _articleService.GetFirst((page - 1) * pageSize, pageSize, hasNulls, sortBy)).ToList();

            int articlesCount = hasNulls ? await _articleService.GetArticlesCount() : await _articleService.GetRatedArticlesCount();

            var pageInfo = new PageInfo()
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = articlesCount, 
                SortByOption = sortBy
            };

            var articleInfos = _mapper.Map<IEnumerable<ArticleInfoViewModel>>(news).ToArray();

            for (int i = 0; i < articleInfos.Count(); i++)
            {
                articleInfos[i].RssName = (await _rssService.GetById(news[i].RssId)).Name;
            }

            return View(new NewsOnPageViewModel() { ArticleInfos = articleInfos, PageInfo = pageInfo });
        }

        public async Task<IActionResult> Article(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var article = _mapper.Map<ArticleViewModel>(await _articleService.GetById(id.Value));

            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }
    }
}

GoodNewsAggregator/GoodNewsAggregator/Views/Navigation/Article.cshtml
@model ArticleViewModel
@{
    ViewData["Title"] = "Article";
}

<div class="">
    <h1 class="display-4 text-center">@Model.Title</h1>
    <div class="text-center">
        <a class="read-next" href="@Model.Source">Читать в источнике</a>
    </div>
    <br/>
    
    <div class="text-left large-size">
        @Html.Raw(Model.Content)
    </div>
    
    <hr />
    <div class="row">
        <input type="hidden" id="articleId" name="articleId" value="@Model.Id" />
        <div class="col-sm-12 azure-background text-center">
            <label for="commentText">Ваш комментарий:</label>
            <textarea name="commentText" class="form-control" placeholder="Оставьте комментарий тут" id="commentText" rows="3"></textarea>
            <div id="error-text" class="red"></div>
            <button class="btn btn-primary write-comment-btn" id="create-comment-btn" onclick="addComment()">Отправить</button>
        </div>
        
        <button id="comments-display-switcher" class="btn btn-primary col-sm-12 mt-4" onclick="getComments('@Model.Id')">Посмотреть комментарии</button>

        <div class="container">
            <div id="comments-container" class="row mt-4"></div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/js/comments.js"></script>
}

GoodNewsAggregator/GoodNewsAggregator/Views/Navigation/Main.cshtml
@using GoodNewsAggregator.Core.DTO;
@using GoodNewsAggregator.Core.Services.Interfaces.Enums
@model NewsOnPageViewModel
@{
    ViewData["Title"] = "Main page";
}

<div class="text-center">
    <h1 class="display-4">Агрегатор хороших новостей</h1>
</div>

@if (Model.ArticleInfos.Count() == 0)
{
    <div class="text-center mt-5">
        <h2>
            Новостей пока нет :(
        </h2>
    </div>
}
else
{
    <form asp-controller="Navigation" asp-action="Main" method="get">
        <input type="hidden" name="page" asp-for="PageInfo" value="@Model.PageInfo.PageNumber" />
        <label asp-for="PageInfo.SortByOption">Сортировка по</label>
        <select name="sortBy" asp-for="PageInfo.SortByOption">
            <option value="@SortByOption.DateTime" selected="@(Model.PageInfo.SortByOption == SortByOption.DateTime)">дате</option>
            <option value="@SortByOption.GoodFactor" selected="@(Model.PageInfo.SortByOption == SortByOption.GoodFactor)">рейтингу</option>
        </select>
        <input type="submit" value="Применить" />
    </form>

    <div class="row">
        @foreach (var article in Model.ArticleInfos)
        {
            <div class="col-sm-6 col-md-4 col-lg-3 mt-2 p-1">
                <div class="article-card">
                    <div class="float-left ml-1">Хорошесть:</div>
                    <div class="text-right mr-1">@article.Date.ToShortDateString()</div>
                    @if (article.GoodFactor.HasValue)
                    {
                        <div class="float-left ml-1 font-weight-bold" data-color="@(article.GoodFactor.Value)">@(article.GoodFactor.Value.ToString("0.##"))</div>
                    }
                    else
                    {
                        <div class="float-left ml-1">-</div>
                    }
                    <div class="text-right mr-1">@article.Date.ToShortTimeString()</div>
                    <div class="text-left ml-1 mr-1 mt-1">
                        Источник:
                        <a class="read-next source-link" href="@article.Source">@article.RssName</a>
                    </div>
                    <div class="text-left ml-1 mr-1 mt-1 mb-1">
                        <a class="read-next title-link" asp-action="Article" asp-route-id="@article.Id">@article.Title</a>
                    </div>
                </div>
            </div>
        }
    </div>

    <div class="text-center">
        <pagination page="Model.PageInfo" page-action="Main"></pagination>
    </div>
}

@section Scripts
{
    <script src="~/js/colorization.js" asp-append-version="true"></script>
}