GoodNewsAggregator/GoodNewsAggregator/Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using GoodNewsAggregator.Core.DTO;
using GoodNewsAggregator.Core.Services.Interfaces;
using GoodNewsAggregator.Core.Services.Interfaces.Constants;
using GoodNewsAggregator.DAL.Core.Entities;
using GoodNewsAggregator.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace GoodNewsAggregator.Controllers
{
    [Authorize(Roles = RoleNames.ADMIN)]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<Role> _roleManager;
        private readonly IArticleService _articleService;
        private readonly IMapper _mapper;

        public AdministrationController(RoleManager<Role> roleManager, IMapper mapper, IArticleService articleService)
        {
            _roleManager = roleManager;
            _mapper = mapper;
            _articleService = articleService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await GetAdminInfo());
        }

        [HttpPost]
        public async Task<IActionResult> Aggregate()
        {
            await _articleService.AggregateNews();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Rate()
        {
            await _articleService.RateNews();

            return RedirectToAction("Index");
        }

        public IActionResult Roles()
        {
            return View(_mapper.Map<IEnumerable<RoleDto>>(_roleManager.Roles) );
        }

        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleDto roleDto)
        {
            await _roleManager.CreateAsync(new Role(){Name = roleDto .Name});
            return RedirectToAction(nameof(Roles));
        }

        public async Task<IActionResult> DeleteRole(Guid id)
        {
            await _roleManager.DeleteAsync(await _roleManager.FindByIdAsync(id.ToString()));
            return RedirectToAction(nameof(Roles));
        }

        private async Task<AdminInfo> GetAdminInfo()
        {
            var count = await _articleService.GetArticlesCount();
            var rated = await _articleService.GetRatedArticlesCount();

            return new AdminInfo() { ArticleCount = count, RatedArticles = rated };
        }
    }
}

GoodNewsAggregator/GoodNewsAggregator/Controllers/RssController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GoodNewsAggregator.Core.Services.Interfaces;
using GoodNewsAggregator.Core.DTO;
using GoodNewsAggregator.Core.Services.Interfaces.Constants;
using Microsoft.AspNetCore.Authorization;

namespace GoodNewsAggregator.Controllers
{
    [Authorize(Roles = RoleNames.ADMIN)]
    public class RssController : Controller
    {
        private readonly IRssService _rssService;

        public RssController(IRssService rssService)
        {
            _rssService = rssService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _rssService.GetAll());
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            return await FindRss(id);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            return await FindRss(id);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            var rss = await _rssService.GetById(id.Value);
            await _rssService.Remove(rss);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, RssDto rss)
        {
            if (id != rss.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _rssService.Update(rss);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await RssExists(rss.Id)))
                    {
                        return NotFound();
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(rss);
        }

        private async Task<bool> RssExists(Guid id)
        {
            return await _rssService.GetById(id) != null;
        }

        private async Task<IActionResult> FindRss(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rss = await _rssService.GetById(id.Value);
            if (rss == null)
            {
                return NotFound();
            }

            return View(rss);
        }
    }
}

GoodNewsAggregator/GoodNewsAggregator/Views/Administration/CreateRole.cshtml
@model GoodNewsAggregator.Core.DTO.RoleDto

@{
    ViewData["Title"] = "Create Role";
}

<h1>Создать</h1>

<h4>Роль</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-light mb-2" asp-action="Roles">Назад к таблице</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoodNewsAggregator/GoodNewsAggregator/Views/Administration/Index.cshtml
@model AdminInfo

@{
    ViewData["Title"] = "Admin Panel";
}

<h1>Панель администратора</h1>

<form method="post" asp-controller="Rss" asp-action="Index">
    <input class="mb-2" type="submit" value="Rss источники" />
</form>

<form method="post" asp-controller="Administration" asp-action="Roles">
    <input class="mb-2" type="submit" value="Управление ролями" />
</form>

<br />

<table class="table">
    <thead>
        <tr>
            <th>
                Количество новостей
            </th>
            <th>
                Описание
            </th>
            <th>
                Действие
            </th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            @Model.ArticleCount
        </td>
        <td>
            Общее количество
        </td>
        <td>
            <form method="post" asp-controller="Administration" asp-action="Aggregate">
                <input class="mb-2" type="submit" value="Собрать" />
            </form>
        </td>
    </tr>
    <tr>
        <td>
            @(Model.ArticleCount - Model.RatedArticles)
        </td>
        <td>
            Нужно оценить
        </td>
        <td>
            <form method="post" asp-controller="Administration" asp-action="Rate">
                <input class="mb-2" type="submit" value="Оценить (30)" />
            </form>
        </td>
    </tr>
    </tbody>
</table>

<br />

<div>
    <a class="btn btn-light mb-2" asp-controller="Account" asp-action="MyAccount">Назад в аккаунт</a>
</div>

GoodNewsAggregator/GoodNewsAggregator/Views/Administration/Roles.cshtml
@using GoodNewsAggregator.Core.Services.Interfaces.Constants
@model IEnumerable<GoodNewsAggregator.Core.DTO.RoleDto>

@{
    ViewData["Title"] = "Role Names";
}

<h1>Роли</h1>

<p>
    <a asp-action="CreateRole">Создать новую роль</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            Название
        </th>
        <th>
            Действие
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (item.Name != RoleNames.ADMIN && item.Name != RoleNames.USER)
                {
                    <a asp-action="DeleteRole" asp-route-id="@item.Id">Удалить</a>
                }
            </td>
        </tr>
    }
    </tbody>
</table>

<div>
    <a class="btn btn-light mb-2" asp-action="Index">Назад в панель администрирования</a>
</div>